apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: dev-pipeline
  namespace: precatorios-dev
spec:
  tasks:
    - name: git-fetch
      params:
        - name: url
          value: 'https://github.com/danielbraga/workshop_3scale_fruits-api.git'
        - name: revision
          value: ''
        - name: refspec
          value: ''
        - name: submodules
          value: 'true'
        - name: depth
          value: '1'
        - name: sslVerify
          value: 'true'
        - name: crtFileName
          value: ca-bundle.crt
        - name: subdirectory
          value: ''
        - name: sparseCheckoutDirectories
          value: ''
        - name: deleteExisting
          value: 'true'
        - name: httpProxy
          value: ''
        - name: httpsProxy
          value: ''
        - name: noProxy
          value: ''
        - name: verbose
          value: 'true'
        - name: gitInitImage
          value: >-
            registry.redhat.io/openshift-pipelines/pipelines-git-init-rhel8@sha256:66f219b4d54a41b945cb5715ecd1fbb5d25431cf8dad4b06914a4cdc65b298cc
        - name: userHome
          value: /home/git
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: source
    - name: maven
      params:
        - name: MAVEN_IMAGE
          value: >-
            registry.redhat.io/ubi8/openjdk-17@sha256:a8165bc2cd5051a96d6937e25ed03155bbd4b731da6e58cebfe2ea83209c16d8
        - name: GOALS
          value:
            - clean
            - package
        - name: MAVEN_MIRROR_URL
          value: ''
        - name: SERVER_USER
          value: ''
        - name: SERVER_PASSWORD
          value: ''
        - name: PROXY_USER
          value: ''
        - name: PROXY_PASSWORD
          value: ''
        - name: PROXY_PORT
          value: ''
        - name: PROXY_HOST
          value: ''
        - name: PROXY_NON_PROXY_HOSTS
          value: ''
        - name: PROXY_PROTOCOL
          value: http
        - name: CONTEXT_DIR
          value: .
      runAfter:
        - git-fetch
      taskRef:
        kind: ClusterTask
        name: maven
      workspaces:
        - name: source
          workspace: source
        - name: maven-settings
          workspace: source
    - name: buildah
      params:
        - name: IMAGE
          value: >-
            image-registry.openshift-image-registry.svc:5000/precatorios-dev/fruits-api:1.0
        - name: BUILDER_IMAGE
          value: >-
            registry.redhat.io/rhel8/buildah@sha256:b48f410efa0ff8ab0db6ead420a5d8d866d64af846fece5efb185230d7ecf591
        - name: STORAGE_DRIVER
          value: vfs
        - name: DOCKERFILE
          value: ./Dockerfile
        - name: CONTEXT
          value: .
        - name: TLSVERIFY
          value: 'false'
        - name: FORMAT
          value: oci
        - name: BUILD_EXTRA_ARGS
          value: '--build-arg PIP_VALUE=http://ifconfig.me'
        - name: PUSH_EXTRA_ARGS
          value: ''
        - name: SKIP_PUSH
          value: 'false'
      runAfter:
        - sonarqube-scanner
      taskRef:
        kind: ClusterTask
        name: buildah
      workspaces:
        - name: source
          workspace: source
    - name: sonarqube-scanner
      params:
        - name: SONAR_HOST_URL
          value: 'https://sonarcloud.io'
        - name: SONAR_PROJECT_KEY
          value: danielbraga_workshop_3scale_fruits-api
        - name: PROJECT_VERSION
          value: '1.0'
        - name: SOURCE_TO_SCAN
          value: src/main/java
        - name: SONAR_ORGANIZATION
          value: danielbraga
        - name: SONAR_SCANNER_IMAGE
          value: 'docker.io/sonarsource/sonar-scanner-cli:5.0.1'
        - name: SONAR_LOGIN_KEY
          value: username
        - name: SONAR_PASSWORD_KEY
          value: password
        - name: SONAR_TOKEN
          value: d53268774de2953d234769f34f8f33cbe0e6fbc7
      runAfter:
        - maven
      taskRef:
        kind: Task
        name: sonarqube-scanner
      workspaces:
        - name: source
          workspace: source
        - name: sonar-settings
          workspace: source
        - name: sonar-credentials
          workspace: source
    - name: openshift-client
      params:
        - name: SCRIPT
          value: 'oc set image deploy/fruits fruits=fruits-api:1.0'
        - name: VERSION
          value: latest
      runAfter:
        - buildah
      taskRef:
        kind: ClusterTask
        name: openshift-client
      workspaces:
        - name: kubeconfig-dir
          workspace: source
  workspaces:
    - name: source
