apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: demo-secret.0.8.1
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend-0.8.1
    kind: SecretStore
  target:
    name: demo-secret-0.8.1
  dataFrom:
  - extract:
      key: "redhat/secrets"
