apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bgd-app
spec:
  destination:
    namespace: user1-bgd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: documentation/modules/ROOT/examples/bgd
    repoURL: https://github.com/danielbraga/openshift-gitops-workshop
    targetRevision: demo-workshop
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
